#
# Dictionary - class repesenting dictionary based on given input words
#

class Dictionary
  def initialize(words)
    @words = words
  end
  
  #
  # Selects words from the dictionary that can be generated by the given tiles
  # Returns: Array
  #
  def match(tiles)
    @words.select do |word|
      word_array = word.split(//)
      tiles_copy = tiles.dup
      word_array.all? do |letter|
        index = tiles_copy.index(letter)
        index && tiles_copy.delete_at(index)
      end
    end
  end
end # end Dictionary